export async function GET() {
  const data = [
    {
      art: "Mystifying Maze",
      art_face: null,
      art_num: null,
      art_set: null,
      bgart1: null,
      bgart1_face: null,
      bgart1_num: null,
      bgart1_set: null,
      bgart2: null,
      bgart2_face: null,
      bgart2_num: null,
      bgart2_set: null,
      bgart3: null,
      bgart3_face: null,
      bgart3_num: null,
      bgart3_set: null,
      child_type: "noChild",
      display_name: "Nothing Here Yet",
      name: "nothingHereYet_none",
      parent: "none",
    },
    {
      art: "Mystifying Maze",
      art_face: null,
      art_num: null,
      art_set: null,
      bgart1: null,
      bgart1_face: null,
      bgart1_num: null,
      bgart1_set: null,
      bgart2: null,
      bgart2_face: null,
      bgart2_num: null,
      bgart2_set: null,
      bgart3: null,
      bgart3_face: null,
      bgart3_num: null,
      bgart3_set: null,
      child_type: "noChild",
      display_name: "Nothing Here Yet",
      name: "nothingHereYet_none",
      parent: "none",
    },
  ];
  //   return new Response.json([{item: 1}, {item: 2}])
  return "hello world";
}
