export function GET() {
  const data = [
    {
      name: "starting_none",
      display_name: "Starting",
      parent: "none",
      child_type: "newStack",
      art: null,
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: null,
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: null,
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: null,
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "lands_starting",
      display_name: "Lands",
      parent: "starting_none",
      child_type: "newStack",
      art: "Flooded Strand",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Field of Ruin",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Rishadan Port",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: null,
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "fixingLands_lands",
      display_name: "Fixing Lands",
      parent: "lands_starting",
      child_type: "newStack",
      art: "Flooded Strand",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Temple Garden",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Wasteland",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: null,
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "nothingHereYet_none",
      display_name: "Nothing Here Yet",
      parent: "none",
      child_type: "empty",
      art: "Mystifying Maze",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: null,
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: null,
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: null,
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "utilityLands_lands",
      display_name: "Utility Lands",
      parent: "lands_starting",
      child_type: "newStack",
      art: "Field of Ruin",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Ancient Tomb",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Rishadan Port",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Urza's Saga",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "archetypes_starting",
      display_name: "Archetypes",
      parent: "starting_none",
      child_type: "newStack",
      art: "Mayhem Devil",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Emry, Lurker of the Loch",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Expressive Iteration",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Bloodghast",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "shockLands_fixingLands",
      display_name: "Shock Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Hallowed Fountain",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Hallowed Fountain",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Watery Grave",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Blood Crypt",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "fastLands_fixingLands",
      display_name: "Fast Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Inspiring Vantage",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Seachrome Coast",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Darkslick Shores",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Black Cleave Cliffs",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "dualLands_fixingLands",
      display_name: "Duals Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Underground Sea",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Tundra",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Taiga",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Badlands",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "manLands_fixingLands",
      display_name: "Man Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Celestial Colonnade",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Hissing Quagmire",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Restless Spire",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Creeping Tar Pit",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "tangoLands_fixingLands",
      display_name: "Tango Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Prairie Stream",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Sunken Hollow",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Smoldering Marsh",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Cinder Glade",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
    {
      name: "slowLands_fixingLands",
      display_name: "Slow Lands",
      parent: "fixingLands_lands",
      child_type: "cardList",
      art: "Deathcap Glade",
      art_set: null,
      art_num: null,
      art_face: null,
      bgart1: "Deserted Beach",
      bgart1_set: null,
      bgart1_num: null,
      bgart1_face: null,
      bgart2: "Dreamroot Cascade",
      bgart2_set: null,
      bgart2_num: null,
      bgart2_face: null,
      bgart3: "Haunted Ridge",
      bgart3_set: null,
      bgart3_num: null,
      bgart3_face: null,
    },
  ];

  const json = JSON.stringify(data);

  return new Response(json, {
    headers: {
      "Content-Type": "application/json",
    },
  });
}
